// <auto-generated />
using System;
using MicroservicesIdentity.Services.EventAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MicroservicesIdentity.Services.EventAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MicroservicesIdentity.Services.EventAPI.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 3, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Location = "Test Location 1",
                            Name = "The Best Conference Ever",
                            StartTime = new DateTime(2024, 3, 6, 12, 33, 14, 258, DateTimeKind.Local).AddTicks(9340)
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 3, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Location = "Test Location 2",
                            Name = "The Second Best Conference Ever",
                            StartTime = new DateTime(2024, 3, 6, 12, 33, 14, 258, DateTimeKind.Local).AddTicks(9380)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
